defaults:
  run:
    working-directory: test-graal
jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        components: native-image
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: '17'
        version: latest
    - continue-on-error: true
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        bb: latest
        lein: latest
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: deps-${{ hashFiles('deps.edn') }}
        path: '~/.m2/repository

          ~/.gitlibs

          ~/.deps.clj

          '
        restore-keys: deps-
    - continue-on-error: true
      run: bb run-graal-tests
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
name: Graal tests
on:
  repository_dispatch:
    types: trigger-ga___graal-tests.yml
