jobs:
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        lein: latest
    - continue-on-error: true
      id: cache-deps
      uses: actions/cache@v4
      with:
        key: deps-${{ hashFiles('project.clj') }}
        path: ~/.m2/repository
        restore-keys: deps-
    - continue-on-error: true
      run: lein test-ci
    strategy:
      matrix:
        java:
        - '17'
        - '19'
        - '21'
        os:
        - ubuntu-latest
name: Main tests
on:
  repository_dispatch:
    types: trigger-ga___main-tests.yml
